// Extracts the design system out of the React Native prototype into plain
// CSS + SVG, so the tokens stay in lockstep with the app instead of drifting.
//
//   node scripts/extract-tokens.mjs [path-to-plt-app-prototype]
//
// Reads:  src/theme/brands.ts   → per-brand colour collections (DS names)
//         src/components/BrandLogo.tsx → brand wordmark SVGs
// Writes: css/tokens.css        → :root + [data-brand="…"] custom properties
//         assets/logos/<brand>.svg
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = process.argv[2] ?? join(HERE, '..', '..', 'plt-app-prototype');
const brandsSrc = readFileSync(join(APP, 'src/theme/brands.ts'), 'utf8');
const logoSrc = readFileSync(join(APP, 'src/components/BrandLogo.tsx'), 'utf8');

const BRANDS = ['plt', 'debenhams', 'boohoo', 'boohooman', 'karenmillen'];

// ── colours ─────────────────────────────────────────────────────────────
// DS_SYSTEM block (shared greys + system ramp)
const sysBlock = brandsSrc.slice(
  brandsSrc.indexOf('const DS_SYSTEM'),
  brandsSrc.indexOf('} as const', brandsSrc.indexOf('const DS_SYSTEM'))
);
const kv = (block) =>
  [...block.matchAll(/([a-zA-Z0-9]+):\s*'(#[0-9A-Fa-f]{3,8})'/g)].map((m) => [m[1], m[2]]);
const system = Object.fromEntries(kv(sysBlock));

// per-brand makePalette({...}) argument blocks
const palettes = {};
for (const b of BRANDS) {
  const at = brandsSrc.indexOf(`id: '${b}',`);
  const start = brandsSrc.indexOf('makePalette({', at);
  const end = brandsSrc.indexOf('}),', start);
  palettes[b] = Object.fromEntries(kv(brandsSrc.slice(start, end)));
}

// kebab-case for CSS custom property names (grey05 → grey-05 for readability)
const cssName = (k) =>
  '--' +
  k
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .toLowerCase();

// ── typography / shape / brand style — stable values from the theme ─────
const FONTS = {
  plt: { family: 'Roboto', regular: 400, medium: 500, semibold: 600, bold: 700, light: 400, display: "'Cardo'", displayStyle: 'italic', displayWeight: 400 },
  debenhams: { family: 'Geologica', regular: 300, medium: 600, semibold: 600, bold: 600, light: 300, display: "'Geologica'", displayStyle: 'normal', displayWeight: 300 },
  boohoo: { family: 'Montserrat', regular: 500, medium: 600, semibold: 600, bold: 700, light: 400, display: "'Montserrat'", displayStyle: 'normal', displayWeight: 600 },
  boohooman: { family: 'Montserrat', regular: 500, medium: 600, semibold: 600, bold: 700, light: 400, display: "'Montserrat'", displayStyle: 'normal', displayWeight: 600 },
  karenmillen: { family: 'Jost', regular: 400, medium: 500, semibold: 600, bold: 700, light: 300, display: "'Jost'", displayStyle: 'normal', displayWeight: 400 },
};
const RADIUS = { plt: 0, debenhams: 4, boohoo: 4, boohooman: 4, karenmillen: 0 };
const BUTTON_RADIUS = { plt: 0, debenhams: 4, boohoo: 4, boohooman: 4, karenmillen: 4 }; // DS Button frames: KM buttons are 4
const CAPS = { plt: 'uppercase', debenhams: 'none', boohoo: 'none', boohooman: 'none', karenmillen: 'none' };
const BLOCK_GAP = { plt: 0, debenhams: 2, boohoo: 2, boohooman: 2, karenmillen: 2 };
const NAME = { plt: 'PrettyLittleThing', debenhams: 'Debenhams', boohoo: 'boohoo', boohooman: 'boohooMAN', karenmillen: 'Karen Millen' };

// SEEL / Deliver+ per-brand treatment (SEEL-Enhancements-2026 frames)
const SEEL = {
  plt: { bg: '#E7ADA2', fg: '#000000', learn: '#000000', check: '#5F0000', onCheck: '#FFFFFF' },
  debenhams: { bg: '#E8F4F2', fg: '#000000', learn: '#00787D', check: '#00787D', onCheck: '#FFFFFF' },
  boohoo: { bg: '#FFE0EB', fg: '#000000', learn: '#000000', check: '#BB305F', onCheck: '#FFFFFF' },
  boohooman: { bg: '#101010', fg: '#FFFFFF', learn: '#FFFFFF', check: '#01FE8A', onCheck: '#000000' },
  karenmillen: { bg: '#000000', bg2: '#161616', fg: '#FFFFFF', learn: '#FFFFFF', check: '#FFFFFF', onCheck: '#000000' },
};

// ── emit tokens.css ──────────────────────────────────────────────────────
let css = `/* GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
 * Source of truth: plt-app-prototype/src/theme/brands.ts (which is itself
 * lifted from the Debenhams Group Design System Figma, per-brand exact).
 * Re-run the script after the prototype's tokens change. */

:root {
  /* spacing scale */
  --space-xs: 4px; --space-sm: 8px; --space-md: 12px;
  --space-lg: 16px; --space-xl: 24px; --space-xxl: 32px;

  /* shared system ramp (identical across brand frames) */
`;
for (const [k, v] of Object.entries(system)) css += `  ${cssName(k)}: ${v};\n`;
css += `
  /* shadows */
  --shadow-card: 0 4px 10px rgba(22, 19, 20, 0.06);
  --shadow-float: 0 8px 18px rgba(22, 19, 20, 0.14);
  --shadow-card-action: 0 0 14px -4px rgba(0, 0, 0, 0.25);
  --shadow-icon-puck: 0 0 14px -4px rgba(0, 0, 0, 0.18);
}
`;

for (const b of BRANDS) {
  const f = FONTS[b];
  css += `\n[data-brand="${b}"] {\n  --brand-name: '${NAME[b]}';\n`;
  for (const [k, v] of Object.entries(palettes[b])) css += `  ${cssName(k)}: ${v};\n`;
  css += `  --ink: var(--soft-black);
  --paper: var(--background-white);
  --stone: var(--grey-4);
  --danger: var(--red);
  --font: '${f.family}', sans-serif;
  --font-display: ${f.display}, serif;
  --font-display-style: ${f.displayStyle};
  --w-regular: ${f.regular};
  --w-medium: ${f.medium};
  --w-semibold: ${f.semibold};
  --w-bold: ${f.bold};
  --w-light: ${f.light};
  --w-display: ${f.displayWeight};
  --radius: ${RADIUS[b]}px;
  --radius-button: ${BUTTON_RADIUS[b]}px;
  --caps: ${CAPS[b]};
  --block-gap: ${BLOCK_GAP[b]}px;
  --seel-bg: ${SEEL[b].bg};
  --seel-bg-2: ${SEEL[b].bg2 ?? SEEL[b].bg};
  --seel-fg: ${SEEL[b].fg};
  --seel-learn: ${SEEL[b].learn};
  --seel-check: ${SEEL[b].check};
  --seel-on-check: ${SEEL[b].onCheck};
}\n`;
}
writeFileSync(join(HERE, '..', 'css', 'tokens.css'), css);
console.log('css/tokens.css written,', css.length, 'bytes');

// ── brand wordmark SVGs ─────────────────────────────────────────────────
// MARKS map entries: `<id>: { xml: \`<svg …>\`, … }`; PLT's own logo lives in
// PLTLogo.tsx, so BrandLogo's MARKS covers the other four.
// entries carry scale/ratio before xml — match lazily across the object
const marks = [...logoSrc.matchAll(/(\w+): \{[^`]*?xml: `(<svg[\s\S]*?<\/svg>)`/g)];
for (const [, id, xml] of marks) {
  writeFileSync(join(HERE, '..', 'assets', 'logos', `${id}.svg`), xml.replaceAll('{C}', '#242424'));
}
console.log('logos:', marks.map((m) => m[1]).join(', '));

const pltLogoSrc = readFileSync(join(APP, 'src/components/PLTLogo.tsx'), 'utf8');
const pltXml = pltLogoSrc.match(/`(<svg[\s\S]*?<\/svg>)`/)?.[1];
if (pltXml) {
  writeFileSync(join(HERE, '..', 'assets', 'logos', 'plt.svg'), pltXml.replaceAll('{C}', '#242424'));
  console.log('logos: plt');
}

// ── DS icons used by the library page ───────────────────────────────────
// Pulled from the generated dsIcons.ts; {C} → currentColor so CSS colours
// them, and the missing stroke-width is baked per the app's normalisation
// (target 1.15pt at a 24px box → 1.15 / innerScale in glyph units).
const dsSrc = readFileSync(join(APP, 'src/components/dsIcons.ts'), 'utf8');
const WANT = ['ds-tick', 'ds-delivery', 'ds-order', 'ds-time', 'ds-wishlist', 'ds-bookmark', 'ds-quick-add', 'ds-bag', 'ds-heart-outline', 'ds-account', 'ds-addresses', 'ds-unlimited', 'ds-support', 'ds-lock-fill'];
const icons = {};
for (const name of WANT) {
  const m = dsSrc.match(new RegExp(`'${name}':\\s*\`(<svg[\\s\\S]*?<\\/svg>)\``));
  if (!m) continue;
  let xml = m[1].replaceAll('{C}', 'currentColor');
  const scale = Number(xml.match(/scale\(([\d.]+)\)/)?.[1] ?? 1) || 1;
  const sw = (1.15 / scale).toFixed(3);
  xml = xml.replace(/stroke-width="[\d.]+"/g, `stroke-width="${sw}"`).replace('<svg ', `<svg stroke-width="${sw}" `);
  icons[name] = xml;
}
writeFileSync(
  join(HERE, '..', 'js', 'ds-icons.js'),
  '// GENERATED by scripts/extract-tokens.mjs — DS glyphs for the library page.\n' +
    'window.DS_ICONS = ' + JSON.stringify(icons, null, 1) + ';\n'
);
console.log('js/ds-icons.js:', Object.keys(icons).join(', '));
